Create P30
DeedeeDL/happy-coding pull request #35
Opened 2024-02-12 10:01 UTC by DeedeeDL

The program will calculate the cube of an user input number

2024-02-12 16:04 UTC, andreiursudev requested changes

2024-02-12 16:04 UTC, andreiursudev commented on src/main/java/org/example/P30_cubeOfANumber.java
> +public class P30_cubeOfANumber {
Use UpperCamelCase formatting for naming classes.

2024-02-12 19:51 UTC, DeedeeDL commented on src/main/java/org/example/P30_cubeOfANumber.java
> +public class P30_cubeOfANumber {
Done

2024-02-13 07:08 UTC, andreiursudev approved these changes

2024-02-14 07:47 UTC, merged