Create C03_02
DeedeeDL/happy-coding pull request #37
Opened 2024-02-14 09:54 UTC by DeedeeDL

The program will calculate the sum of the first 10 numbers.

2024-02-14 10:39 UTC, andreiursudev requested changes

2024-02-14 10:39 UTC, andreiursudev commented on src/main/java/org/example/C03_02_SumOfNumbers.java
> +        int suma = 0;
Use english.

2024-02-15 17:56 UTC, DeedeeDL commented on src/main/java/org/example/C03_02_SumOfNumbers.java
> +        int suma = 0;
Done

2024-03-02 08:16 UTC, andreiursudev approved these changes

2024-03-05 09:06 UTC, merged

2024-03-05 14:49 UTC, andreiursudev commented on src/main/java/org/example/C03_02_SumOfNumbers.java
> +        System.out.println("Suma primelor 10 numere este: " + sum);
This is still in romanian.