Create C03_03
DeedeeDL/happy-coding pull request #38
Opened 2024-02-14 10:09 UTC by DeedeeDL

The program will calculate the sum of n numbers (in this example, n is 7, so it calculates the sum of first 7 numbers)

2024-02-14 10:40 UTC, andreiursudev requested changes

2024-02-14 10:40 UTC, andreiursudev commented on src/main/java/org/example/C03_03_SumOfNNumbers.java
> +        int suma = 0;
Use english.

2024-02-15 17:58 UTC, DeedeeDL commented on src/main/java/org/example/C03_03_SumOfNNumbers.java
> +        int suma = 0;
Done

2024-03-02 08:18 UTC, andreiursudev requested changes

2024-03-02 08:18 UTC, andreiursudev commented on src/main/java/org/example/C03_03_SumOfNNumbers.java
> +        System.out.println("Suma numerelor este de: " + sum);
Use english.

2024-03-07 15:25 UTC, DeedeeDL commented on src/main/java/org/example/C03_03_SumOfNNumbers.java
> +        System.out.println("Suma numerelor este de: " + sum);
done

2024-03-07 15:58 UTC, andreiursudev approved these changes

2024-03-22 12:34 UTC, merged