Created C05_03
DeedeeDL/happy-coding pull request #40
Opened 2024-02-15 15:03 UTC by DeedeeDL

The program will calculate the sum of the elements in the array

2024-02-15 15:07 UTC, andreiursudev requested changes

2024-02-15 15:07 UTC, andreiursudev commented on src/main/java/org/example/C05_03_SumOfElements.java
> +            sum = sum+a;
Dont forget to format code.

2024-03-07 15:26 UTC, DeedeeDL commented on src/main/java/org/example/C05_03_SumOfElements.java
> +            sum = sum+a;
done

2024-03-07 15:59 UTC, andreiursudev approved these changes

2024-03-22 12:35 UTC, merged