Create C03_09
DeedeeDL/happy-coding pull request #52
Opened 2024-03-01 10:03 UTC by DeedeeDL

This program will create a pattern of asterix depending on how many rows user entered

2024-03-02 08:08 UTC, andreiursudev requested changes

2024-03-02 08:08 UTC, andreiursudev commented on src/main/java/org/example/C03_09_AsterixPattern.java
> +public class C03_09_AsterixPattern {
Rename to AsterixTrianglePattern

2024-03-05 08:39 UTC, DeedeeDL commented on src/main/java/org/example/C03_09_AsterixPattern.java
> +public class C03_09_AsterixPattern {
Done

2024-03-05 14:46 UTC, andreiursudev approved these changes

2024-03-07 14:55 UTC, merged